Updating pom to use new 1.1.4 parent-pom
dropwizard-bundles/dropwizard-version-bundle pull request #14
Opened 2017-10-04 20:42 UTC by zachschultz

2017-10-05 21:23 UTC, alexwen commented on pom.xml
> +    <version>1.1.4-SNAPSHOT</version>
The parent here should be the release version of Dropwizard, `1.1.4`.

2017-10-09 15:21 UTC, alexwen requested changes

2017-10-09 15:21 UTC, alexwen commented on pom.xml
> +  <version>1.1.4</version>  <!-- Make sure to keep this in sync with the parent pom version above. -->
The non-release version just be `1.1.4-SNAPSHOT`.

2017-10-09 17:11 UTC, alexwen commented
@zachschultz looks like this build is failing due to using a deprecated method:
https://travis-ci.org/dropwizard-bundles/dropwizard-version-bundle/builds/285665950?utm_source=github_status&utm_medium=notification

We will want to stop using the Throwables method flagged by the build.

2017-10-09 17:32 UTC, bbeck commented
Closing in favor of #15.

2017-10-09 17:32 UTC, closed without merging